language: en

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
- name: DucklingHTTPExtractor
  url: http://duckling:8000
  dimensions:
  - email
  - email_addr
  - duration
  - time
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  max_history: 2
  batch_strategy: sequence
  epochs: 100
  evaluate_on_number_of_examples: 0
- name: MappingPolicy
- name: FormPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.3
  core_threshold: 0.3
  fallback_action_name: "action_default"
