imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: mail_blacklist.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/" }
    - { resource: "@UserBundle/Resources/config/" }
    - { resource: "@TopicBundle/Resources/config/" }
    - { resource: "@CoreBundle/Resources/config/" }
    - { resource: "@PaymentBundle/Resources/config/" }
    - { resource: "@DiaryBundle/Resources/config/" }
    - { resource: "@FaqBundle/Resources/config/" }
    - { resource: "@TicketBundle/Resources/config/" }
    - { resource: "@InternshipBundle/Resources/config/" }
    - { resource: "@PartnershipBundle/Resources/config/" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    redirection_url_after_access_denied_exception: homepage

framework:
    #esi: ~ # Pour utiliser les tags ESI dans les templates Twig
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        website: InfoPlus
        pathDefault: 'http://localhost:8000/web/'


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                DAY: DoctrineExtensions\Query\Mysql\Day
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR:  DoctrineExtensions\Query\Mysql\Year
                DATE: DoctrineExtensions\Query\Mysql\Date
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~

        CrudThumb:
            quality: 90
            filters:
                thumbnail: { size: [75, 34], mode: outbound }

        topicThumb:
            quality: 80
            filters:
                thumbnail: { size: [170, 100], mode: outbound }

        topicFull:
            quality: 80
            filters:
                thumbnail: { size: [750, 343], mode: outbound }

        topicShow:
            quality: 80
            filters:
                thumbnail: { size: [650, 400], mode: outbound }

        UserThumb:
            quality: 80
            filters:
              thumbnail: { size: [100, 100], mode: outbound }

        UserCrudThumb:
            quality: 80
            filters:
              thumbnail: { size: [40, 50], mode: outbound }

        diaryThumb:
            quality: 80
            filters:
               thumbnail: { size: [180, 150], mode: outbound }

services:
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
    twig.extension.date:
            class: Twig_Extensions_Extension_Date
            tags:
                - { name: twig.extension }
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }
    twig.extension.array:
            class: Twig_Extensions_Extension_Array
            tags:
                - { name: twig.extension }
    twig.extension.i18n:
            class: Twig_Extensions_Extension_I18n
            tags:
                - { name: twig.extension }

ewz_recaptcha:
    public_key: 6LemfyAUAAAAAKAsYoGU0O5LrdpiTv-vDDvqmUPm
    private_key: 6LemfyAUAAAAAHPPDhgZP6F9lKZjBInnLUjUNstc
    # Not needed as "%kernel.default_locale%" is the default value for the locale key
    locale_key:  %kernel.default_locale%
    locale_from_request: true

app:
    max_category_per_page: 10

topic:
    max_topic_per_page: 10

user:
    max_rank_per_page: 10
    max_user_per_page: 10

diary:
    max_diary_per_page: 10
    max_diary_home_page: 3


faq:
    max_faq_per_page: 10

payment:
    max_invoice_per_page: 10
    max_product_per_page: 10

ticket:
    max_ticket_per_page: 10

partnership:
    max_partnership_per_page: 10
    
internship:
    max_internship_per_page: 10
