services:

    partnership.partnership_repository:
                class: PartnershipBundle\Repository\PartnershipRepository
                factory: ["@doctrine.orm.default_entity_manager", getRepository]
                arguments: ['PartnershipBundle\Entity\Partnership']
                lazy: true